### ISSUE TITLE
Useless links

### ISSUE THREAD

**Issue by r1ddle1** [KaydemonLP/Open-Fortress-Source#31]
Hello! In the LINUX.md there are useless links because they just don't work.
Could you please fix 'em?

![image](https://user-images.githubusercontent.com/46493085/81537128-6436ef80-9375-11ea-8e6a-189aacba2422.png)

**Comment by Nopey** [comment]
This should be fixed now, thanks!

**Comment by r1ddle1** [comment]
Okay, thank you!
