### ISSUE TITLE
of_spawn_with_weapon only takes one argument

### ISSUE THREAD

**Issue by kyokyoknutt** [KaydemonLP/Open-Fortress-Source#46]
...meaning you can't force a specific weapon layout, just... ***a*** starting weapon.

I tried seeing if I could allow for multiple arguments through commas, but that would require a stringstream... which Source SDK 2013 doesn't seem to support. Argh.

Any advice on this would be appreciated!

**Comment by int-72h** [comment]
This may be a bit bone-headed of me, but couldn't you make a class/object which has the properties of a full weapon loadout and pass that as an arg?

**Comment by kyokyoknutt** [comment]
Wait, idea... what if instead of a ConVar it was a ConCommand? That could take multiple arguments! The only question is, how would I store the args?
Gotta do some more thonkin.

**Comment by int-72h** [comment]
Store it as a convar, but make it a bitmask- each weapon is a bit you can enable (e.g ssg is 100, revolver 10, so bitmask of 110 = 6 in normal numbers)

**Comment by int-72h** [comment]
@kyokyoknutt Have you made any progress on this? I'm bored as anything and may see if I can do this.

**Comment by kyokyoknutt** [comment]
@int-72h I think I remember figuring it out and getting a solution. It might have had a kink though: let me check.

**Comment by kyokyoknutt** [comment]
Yep, I got it figured out already. Thanks @ficool2 for helping me figure out how to process the ConVar string. I just added a failsafe to it where if the loadout fails, it defaults back to the proper loadout for the current mutator. #44 
Thanks for volunteering to give it a shot, though! If you wanna make any changes to streamline it, feel free!

**Comment by kyokyoknutt** [comment]
Gonna close this issue now, just refer to PR #44 if you have any comments or questions.
