### ISSUE TITLE
(CRITICAL) Latest update renders Linux multiplayer servers unusable

### ISSUE THREAD

**Issue by James76931** [KaydemonLP/Open-Fortress-Source#52]
Hi.

I'm running a fresh install of build 937 on my Windows client and Linux server. When trying to connect to the server I am disconnected with the error message in my console: "CL_CopyExistingEntity: missing client entity 2."

Many other users are reporting having a similar issue and after further investigation I can confirm that the issue does not occur when connecting to an OF server running on Windows.

**Comment by zxz41** [comment]
Our Linux builder is (as far as I know) apparently down, I'll see if I can compile the build on a VM and commit it to the SVN. Otherwise I'll ask some of our Linux folks to compile the .so binaries. Sorry for the inconvenience.

**Comment by Terradice** [comment]
fixed.. never commit bin updates without linux build.
