### ISSUE TITLE
No material as to how VAC secure mode is enabled

### ISSUE THREAD

**Issue by hanaral** [KaydemonLP/Open-Fortress-Source#66]
Hi, after searching this git as well as the svn repo I have yet to find how VAC is enabled to access secure servers.  (I'm on Ubuntu)

**Comment by Mangmasta** [comment]
This is a known bug on Linux.  The work around is to add "-secure -steam" to your launch options.  Maybe this issue should be kept open until it's fixed?

**Comment by hanaral** [comment]
It seems like an easy fix for the time being, I do think that this issue should be kept open until it is fixed. I also recommend mentioning this somewhere in the README as it might be the first place people look for a solution.

**Comment by hanaral** [comment]
Closed since another contributer has made a combined issue to the Linux specific bugs.
